### ISSUE TITLE
Twitter video links not working

### ISSUE THREAD

**Issue by peterlymo** [zeronickname/VideoDownloader#2]
is this abandonded?

**Comment by zeronickname** [comment]
Well, it does what it is designed to do. Until/unless it stops working, there is nothing more to do.
So no, it's not abandoned. But there will be no more work done on it (unless there are bug reports)

Do you have a bug to report?

**Comment by peterlymo** [comment]
was trying to see if its support video from twitter...i just like this app and am looking that functionality..

**Comment by zeronickname** [comment]
OK.... twitter [is supported by the latest youtube-dl](https://rg3.github.io/youtube-dl/supportedsites.html) and the version I'm using is a couple of years old and has broken support. I should be able to fix this with a server side update.
Re-opened the issue and changed title...

**Comment by peterlymo** [comment]
well am waiting for the fix and code,,

can i have your email too? if you dont mind...am just a begginer and i real need support from someone who already in this things

**Comment by zeronickname** [comment]
Youtube-dl upgraded to 2017.12.31 server side. No changes required to android app.
I checked with a random twitter video and it works now after the upgrade.

Please let me know if it works for you now.

peterlymo, my profile should have my email address, but I'm not sure if I have the time for supporting you outside of github. Sorry :(

**Comment by zeronickname** [comment]
Assuming fixed and closing bug
