### ISSUE TITLE
how to add video links for download 

### ISSUE THREAD

**Issue by Ramkesh9** [zeronickname/VideoDownloader#3]
i am sharing a link from youtube app to this app , but it saying somthing to contact to you for more details.

**Comment by zeronickname** [comment]
Open the web-browser and browse to a video on [a supported site](https://rg3.github.io/youtube-dl/supportedsites.html).
Share the page to GetMedia using the built-in android share sheet
Wait for download to complete

If you [enable youtube support](https://github.com/zeronickname/VideoDownloader#youtube-support), you can alternatively share the page from the youtube app directly.

**Comment by zeronickname** [comment]
Just saw your edit.

To enable youtube support follow instructions in the readme
>To (re)enable support for youtube, open the app, overflow menu and hit about. Repeat this procedure a further 4 times. Now Youtube links work (note: private links still won't work)

Youtube support is disabled by default to work around play store restrictions

**Comment by zeronickname** [comment]
Assuming fixed and closing bug
