### ISSUE TITLE
Enhancement..Add gigaget as your downloader

### ISSUE THREAD

**Issue by smoochiee** [zeronickname/VideoDownloader#4]
can you add gigaget as your downloader?

**Comment by zeronickname** [comment]
The Android app is just a small wrapper that hits a hosted version of youtube-dl to get the video file URL.
So the list of supported sites is basically whatever is [supported by youtube-dl](https://rg3.github.io/youtube-dl/supportedsites.html)

gigaget is currently not on that list (unless I missed something) 

I'd suggest making it a feature request of youtube-dl: https://github.com/rg3/youtube-dl/

**Comment by zeronickname** [comment]
OK, just looked up gigaget, and it's a download manager. Sorry for misunderstanding your original request.

Is there any documentation on how to do that? I think I explicitly pass an intent to the android Download manager. Does gigaget register as the default downloader on Android?

**Comment by zeronickname** [comment]
Alternatively, I could add the download URL to the clipboard and you can manually paste it into gigaget?

**Comment by smoochiee** [comment]
Im having problem with gigaget...ive implemented your code on my browser...by adding button and get.url..theres no need to share url..

**Comment by smoochiee** [comment]
Newpipe implemented gigaget as there youtube downloader...see newpipe on how they implemented it..

**Comment by smoochiee** [comment]
Or you can use open source multi thread download manager...bcoz default dlmanager to slow..

**Comment by zeronickname** [comment]
Is there even an android version of giganet? Is it open source?

I can't see newpipe using giganet either (as NewPipe is open source and has [a built in downloder](https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_8.png))

So, I'm afraid I'm still not entirely sure what you want. I do not want to incorporate a download manager into this app as I'm trying to keep it as slim as possible.
I'm happy to copy the url into clipboard to allow you to use any other download manager. Beyond that I'm not sure what to suggest. Sorry.

**Comment by zeronickname** [comment]
It shouldn't be too hard to fork the code, use the same backend as I'm using and implement a multi-threaded download manager. But it's not something I want to implement, sorry :(
